language: node_js
node_js:
  - "10"
cache: npm
script: npm run coverage
after_success: npm run coveralls
before_deploy: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist
  fqdn: izenak.eus
  on:
    branch: master
